# Generated by Django 3.1.6 on 2021-02-24 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210222_0910'),
        ('main_app', '0007_topic_img'),
    ]

    operations = [
    ]
